### ISSUE TITLE
gtags-mode--after-save-hook should check whether we are in GLOBAL project

### ISSUE THREAD

**Issue by mandarm** [Ergus/gtags-mode#7]
Whenever gtags-mode is enabled, ```gtags-mode--after-save-hook``` is added to ```after-save-hook```, and runs every time a buffer is saved. This results in spurious error messages like 

```process-file: Setting current directory: Not a directory```

when I am editing files that are not part of any project tagged with GNU global.

Please consider whether it would be a good idea to replace the following condition at the beginning of ```gtags-mode--after-save-hook```

  ```(when (and buffer-file-name```

with something like

  ```(when (and (gtags-root-dir) buffer-file-name```

http://www.emacswiki.org/emacs/GnuGlobal contains the gtags-root-dir function.

```
  (defun gtags-root-dir ()
  "Returns GTAGS root directory or nil if doesn't exist."
  (with-temp-buffer
    (if (zerop (call-process "global" nil t nil "-pr"))
        (buffer-substring (point-min) (1- (point-max)))
      nil)))
```

**Comment by mandarm** [comment]
I'm sorry, I think your code already tries to determine the project root, and store it in a property list, but I did not fully understand your code. Here are some errors from the *Messages* buffer that may help to identify where things go wrong, if I save a file that is not a part of any project.

gtags-mode: Global sync error output:
global: GTAGS not found.
gtags-mode: Sync /bin/global (--print-dbpath): exited abnormally with code 3

**Comment by Ergus** [comment]
Hi @mandarm:

Very thanks for writing and sorry for the issue.
I have received some previous issues about similar problems and they really have to do with the verbosity of my code. Like in this case, they are just warnings that could be ignored. You can reduce the `gtags-mode-verbose-level` to 1 if the messages annoy too much.

The message you see is actually a consequence of calling global to determine if there is a GTAGS_ROOT. Because the "proper" way to determine if there is a gtags root (project-root) is using `--print-dbpath`.

So basically the message you see is the "error" that `global` returns when there is not a gtags root for this project.

This is made every time we save because when we create new files in a project, the file initially does not have a project associated (as there is not filename associated). So the message you see is actually a warning when the test you suggest fails getting a project-root :( mea culpa. 

I will try to add some more heuristics for this specific case in a while. (I just did something similar for the case when gtags/global is not installed)
